# digi-ad/plugin.yaml
identity:
  name: digi-ad
  author: rikiy
  label:
    en_US: Digi-AD Tool
    ja_JP: デジアドツール
  description:
    en_US: A tool to connect Dify with Google BigQuery for ad analysis.
    ja_JP: DifyとGoogle BigQueryを連携し広告分析を行うためのツールです。
provider: "provider/google.yaml"  # ←ここ！パスとスペルを厳密に確認！
